Plugin 'vim-scripts/STL-improved'
Plugin 'vim-scripts/cpp.vim'
"Plugin 'Mizuchi/STL-Syntax'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'vim-scripts/Cpp11-Syntax-Support'
Plugin 'derekwyatt/vim-fswitch'
